import type { Metadata } from "next";
import { Navbar, NavbarBrand, NavbarContent, NavbarItem, Link } from "@nextui-org/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar className="flex justify-start">
          <NavbarContent className="hidden sm:flex gap-4 pl-3">
            <NavbarItem>
              <Link href="/news">News</Link>
            </NavbarItem>
            <NavbarItem>
              <Link href="/contact">Contact</Link>
            </NavbarItem>
          </NavbarContent>
          <div className="flex justify-center">
            <NavbarBrand className="bg-red-500 font-bold text-inherit flex mx-auto">
              <Link className="text-5xl" href="/">Home</Link>
            </NavbarBrand>
          </div>
          </Navbar>
        {children}
      </body>
    </html>
  );
}
