import type { Metadata } from "next";
import Link from 'next/link';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
    <nav className="p-4">
      <div className="container mx-auto flex justify-between items-center">
        <div className="flex-1 flex justify-center">
          <h1 className="text-white text-2xl">Based News</h1>
        </div>
        <div className="hidden md:flex space-x-4">
          <Link href="/" className="text-white"> Home </Link>
          <Link href="/news" className="text-white"> News </Link>
          <Link href="/contact" className="text-white"> Contact </Link>
          <Link href="/stocks" className="text-white"> Stocks </Link>
        </div>
      </div>
    </nav>
        {children}
      </body>
    </html>
  );
}