import type { Metadata } from "next";
import { Navbar, NavbarBrand, NavbarContent, NavbarItem, Link } from "@nextui-org/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar>
          <NavbarContent className="sm:flex gap-9 pl-5">
            <NavbarItem>
              <Link href="/news">News</Link>
            </NavbarItem>
            <NavbarItem>
              <Link href="/contact">Contact</Link>
            </NavbarItem>
            <NavbarItem>
              <Link href="/stocks">Stocks</Link>
            </NavbarItem>
          </NavbarContent>
            <div className="pl-40">
              <div className="pl-40">
                <NavbarBrand className="text-5xl bg-red-500 font-bold flex">
                  <Link href="/">Home</Link>
                </NavbarBrand>
              </div>
            </div>
          </Navbar>
        {children}
      </body>
    </html>
  );
}
